import React from "react";
import HeroSection from "../components/HeroSection";
import { useNavigate, Link } from "react-router-dom";
import { CheckSquare, Calendar, Trophy, Sparkles } from "lucide-react";
import { useSelector } from "react-redux";

const Home = () => {
  const { loading } = useSelector((state) => state.user);
  const navigate = useNavigate();

  if (loading) return null;

  const features = [
    {
      icon: <CheckSquare className="w-8 h-8 text-green-600" />,
      title: "Track Daily Habits",
      description: "Choose from eco-friendly habits or create custom ones. Check them off daily and build momentum.",
    },
    {
      icon: <Calendar className="w-8 h-8 text-green-600" />,
      title: "Build Streaks",
      description: "Visual progress tracking keeps you consistent. Don't break the chain!",
    },
    {
      icon: <Trophy className="w-8 h-8 text-green-600" />,
      title: "Earn Achievements",
      description: "Unlock badges for milestones and share your eco-achievements with friends.",
    },
    {
      icon: <Sparkles className="w-8 h-8 text-green-600" />,
      title: "AI Habit Advisor",
      description: "Get personalised sustainability habits generated by AI based on your goals and schedule.",
    },
  ];

  return (
    <div className="pt-20">
      <HeroSection />

      {/* How it works */}
      <div className="p-6 text-center max-w-3xl mx-auto mt-8">
        <h2 className="text-3xl font-bold mb-3">How HabitLeaf Works</h2>
        <p className="text-gray-600 text-lg">A gamified, AI-powered approach to building sustainable habits that stick.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 px-6 md:px-16 py-10 text-center">
        {features.map((feature, idx) => (
          <div key={idx} className="flex flex-col items-center bg-white rounded-2xl p-6 shadow-sm border border-gray-100 hover:shadow-md transition">
            <div className="p-4 bg-green-50 rounded-2xl flex items-center justify-center mb-4">
              {feature.icon}
            </div>
            <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
            <p className="text-gray-500 text-sm">{feature.description}</p>
          </div>
        ))}
      </div>

      {/* AI Feature highlight banner */}
      <div className="mx-6 md:mx-16 mb-12 rounded-2xl bg-linear-to-r from-green-600 to-emerald-500 p-8 md:p-10 flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="text-white">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-5 h-5" />
            <span className="text-sm font-semibold text-green-200 uppercase tracking-wide">New Feature</span>
          </div>
          <h3 className="text-2xl md:text-3xl font-bold mb-2">AI-Powered Habit Recommendations</h3>
          <p className="text-green-100 text-sm max-w-lg">
            Tell our AI your sustainability goals and available time. Get 5 personalised eco habits generated instantly — complete with impact scores and daily tips.
          </p>
        </div>
        <Link
          to="/ai-advisor"
          className="shrink-0 bg-white text-green-700 font-semibold px-6 py-3 rounded-full shadow hover:bg-green-50 transition text-sm whitespace-nowrap"
        >
          Try AI Advisor →
        </Link>
      </div>

      {/* Community section */}
      <div className="bg-green-700 py-12 text-center">
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Join the HabitLeaf Community</h1>
        <p className="text-gray-200 text-lg max-w-xl mx-auto">
          Connect with like-minded individuals, share your progress, and inspire each other to live more sustainably.
        </p>
        <div className="flex flex-col md:flex-row justify-center gap-6 mt-10 px-4">
          {[
            { name: "Sarah M.", role: "Zero Waste Champion", streak: "45 days" },
            { name: "Mike R.", role: "Green Transport Hero", streak: "23 days" },
            { name: "Emma L.", role: "Water Conservation Expert", streak: "67 days" },
          ].map((member) => (
            <div key={member.name} className="bg-green-600 bg-opacity-90 rounded-xl shadow-xl p-8 w-full md:w-1/4 hover:scale-105 transition duration-300 cursor-pointer">
              <div className="bg-white/20 rounded-full p-5 flex items-center justify-center mb-4 mx-auto w-16 h-16">
                <span className="text-white text-2xl font-bold">{member.name[0]}</span>
              </div>
              <h2 className="text-white font-semibold text-xl">{member.name}</h2>
              <div className="text-gray-100 mt-1 text-sm">{member.role}</div>
              <div className="text-yellow-300 font-bold mt-3">🔥 {member.streak}</div>
            </div>
          ))}
        </div>
        <button
          onClick={() => navigate("/community")}
          className="mt-10 px-8 py-3 bg-white text-green-700 text-base font-semibold rounded-full shadow hover:bg-green-50 transition"
        >
          Join Community →
        </button>
      </div>
    </div>
  );
};

export default Home;
